/// Flutter icons DroneFarm
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DroneFarm
///      fonts:
///       - asset: fonts/DroneFarm.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DroneFarm {
  DroneFarm._();

  static const _kFontFam = 'DroneFarm';
  static const String? _kFontPkg = null;

  static const IconData farm = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drone = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
