/// Flutter icons SprayDroneIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SprayDroneIcon
///      fonts:
///       - asset: fonts/SprayDroneIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SprayDroneIcon {
  SprayDroneIcon._();

  static const _kFontFam = 'SprayDroneIcon';
  static const String? _kFontPkg = null;

  static const IconData spray_robot_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
